spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'Tafadzwa@*25'
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.SQLServerDialect
      show-sql: true
      format_sql: true
    open-in-view: true
server:
  port: 8083

